### PR TITLE
Add `read-quoted-char' handling to the read-funcs setup

### PR DESCRIPTION
**Pull request by stepnem**
This fixes e.g. `quoted-insert' (bound to C-q by default).

### CODE REVIEW

**Comment by stepnem** [comment]
I'm sorry I've missed that, thank you. I have updated the branch with 2
commits fixing the compiler warnings, both those introduced by myself
and another one.

**Comment by cute-jumper** [comment]
Thanks for the quick fix. Do you push your code into the same branch? I can't see the newer commits in this PR.

**Comment by stepnem** [comment]
Yeah, the other commits (on top of the original one from this PR) are
all in master, sorry for the confusion.

**Comment by cute-jumper** [comment]
Can you merge it back to this branch? We don't have to submit another PR for the master branch.

**Comment by stepnem** [comment]
Well, you can just merge or apply the commits any way you wish, as with
any other git repo. Besides that, the other commit is unrelated to the
topic of this PR, so it really doesn't make much sense in a branch named
"read-quoted-char".

**Comment by cute-jumper** [comment]
I think the title or the branch name doesn't matter. The thing that matters is that if you don't merge the code back to this branch or submit a new PR, I can only go to your repo and do a copy & paste. It will lose all the copyright information. I shouldn't do that since you're the author of the code. If we can merge it through this PR, we should be able to keep tracking of the author of every single commit, which would be better. What do you think?

**Comment by stepnem** [comment]
You could have done just `git pull <url to my fork>` followed by `git
push`. There's more to Git than GitHub, fortunately.

Anyway, I've created a new PR, thank you and sorry again for the
inconvenience.

**Comment by cute-jumper** [comment]
You're right. Close this and I'll merge #37

**Pull request closed without merging**
